events {}

http {
    upstream empleados_upstream {
        server empleados-service:8081;
    }

    upstream departamentos_upstream {
        server departamentos-service:8082;
    }

    server {
        listen 80;
        server_name _;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /empleados {
            proxy_pass http://empleados_upstream;
        }

        location /departamentos {
            proxy_pass http://departamentos_upstream;
        }

        location /docs {
            proxy_pass http://empleados_upstream;
        }

        location /openapi.json {
            proxy_pass http://empleados_upstream;
        }

        location / {
            return 404;
        }
    }
}
